### PR TITLE
Multiple file conversion and SQL like auto increment support 

### PR DESCRIPTION
**Pull request by kerekesjoco**
I needed the functionalities above and while I was implementing I fixed some issues and updated dependency.

please feel free to merge if you consider.

======================================

multiple file conversion:
----------------------------
Implemented support for many individual file processing.
grunt documentation: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

auto increment usage:
----------------------
    "field_name":{
      "type": "string",
      "format": "index",
      "from": 10
    }

### CODE REVIEW

**Comment by ducin** [comment]
@kerekesjoco thanks for the contribution! I'm interested in merging, but first I want to understand the new features :)

I was reading the diff, but couldn't get the main point of what new I can do now. Could you describe the new features with an example?

Moreover, could you define whether you have extended grunt-jsonschema-faker (grunt plugin) OR the json-schema-faker (the tool itself)?

**Comment by kerekesjoco** [comment]
I modified just the  grunt-jsonschema-faker. 

For the new features I added examples in Gruntfile.js but I will describe them:

1. Multiple file conversion:
I needed to compile many files and i didn't want to add each manually.
( I want to be able to compile all my files with a single like in other grunt plugins)

Basically with my change you can use something like
```javascript
files: [
    {
        expand: true,
        cwd: "src/data",
        src: "*.schema", // or *.schema if you have other extension for your schema files
        dest: "public/data",
        ext: '.json',   // compiled fie extension if you want to be changed
        rename: function (dest, src){    // renaming if you require
            return dest + "/renamed-"+src;
        }
    }
]
```
Here is an examples, given the following file tree:
```shell
.
├── Gruntfile.js
└── src
    └── data
        ├── products.schema
        ├── ....
        └── person.schema

```
The result after compile would be something like:
```shell
.
├── Gruntfile.js
├── public
│      └── data
│         ├── renamed-products.json
│         ├── ....
│         └── renamed-person.json
└── src
    └── data
        ├── products.schema
        ├── ....
        └── person.schema

```
For this you have example included in main Gruntfile.js.
Please note the syntax above is compatible with other grunt plugins file conversion support.
(grunt documentation: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically)

2. Auto increment: 
I needed to generate a list of products with integer id something like:
```json
[
  {
    "id": 10,
    "Name": "Some name "
  },
  {
    "id": 11,
    "Name": "Some other name"
  },
  ....
  {
    "id": 19,
    "Name": "Lorem ipsum dolor"
  }
]
```
the schema would look like

```json
{
  "type": "object",
  "properties": {
    "id":{
      "type": "string",
      "format": "index",
      "from": 10
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name"
  ]
}
```
You have to modify your Gruntfile.js and add something like:
```javascript
// ...
    list: {
        src: 'test/fixtures/list.json',
        dest: 'tmp/list.json',
        options: {
            size: 10 
        }
    },
// ...
```
For this I added example in Gruntfile.js and added tests in jsonschema_faker_test.js 

If you have any other question please let me know.

**Comment by kerekesjoco** [comment]
I didn't want to close

**Comment by ducin** [comment]
@kerekesjoco thank you very much for the description! Now I got the whole point and I'll include some of your explanation in the README.md.

There's just one thing I'm thinking of unifying - it's how to use the `generators.js` file. Currently it has been used only through `external` option ([code](https://github.com/ducin/grunt-jsonschema-faker/blob/master/tasks/jsonschema_faker.js#L49-L53) and [example](https://github.com/ducin/grunt-jsonschema-faker/blob/master/Gruntfile.js#L66-L87)). I tried to make it generic - if we add any more generators (I know it's very few of them), they will be available with no task code (grunt task file) changes.

What you've suggested is to hardcode adding the new `index` generator inside the grunt task file `tasks/jsonschema_faker.js` - [see PR](https://github.com/ducin/grunt-jsonschema-faker/pull/1/files#diff-99492ad12fac80691babfea948498ef3R32). The result is that if we add any new generators, they would have to be added manually each time, and it's neither flexible nor easy to maintain (hope U know what I mean).

I know that the context in which I was using generators (referencing external files) is different than your context(just generating something). Anyway, I'm thinking of a generic way to add the additional generators. I want to keep this tool as simple as possible for the end users (the KISS principle). I'm wondering, whether this `index` generator wouldn't suit existing architecture better, if it was just a [faker/chance extension](https://github.com/ducin/grunt-jsonschema-faker#extending-dependencies)? The generator doesn't reference any other file - so it's not the `external` option case. But I can't see a reason not to extend the dependent libs so far (I'm opened for discussion, though). Please share your thoughts on this.

PS Currently I'm on vacation, I'll speed up when I get back.

PPS - [this one](https://github.com/ducin/grunt-jsonschema-faker/pull/1/files#diff-99492ad12fac80691babfea948498ef3R57) is a nice catch, really, thank you for your work :)

**Comment by ducin** [comment]
Just one more thing - I'll merge the PR when we get the final vision of the generator. If you have had submitted different PRs for different topics, I'd merge the rest straight away (it's better to have separate PRs for different things, as you can see). But that's ok :), it'll just take few more days to merge :)

**Comment by ducin** [comment]
@kerekesjoco Finally I found time to catch up with the topic. Everything was fine, I just moved the index sql-alike custom format into a new `formats` file, since it's *not* a generator. Thank you for your contribution.

By the way, wouldn't you be interested in contributing to https://github.com/pateketrueke/json-schema-faker? This is the core tool :)

**Pull request merged**
